SELECT CORE_SONG_ARTIST.ARTIST_ID,
	CORE_PLAYLIST.NAME,
	CORE_SONG.NAME,
	CORE_PLAYLIST_SONG.PLAYLIST_ID
FROM CORE_PLAYLIST,
	CORE_PLAYLIST_SONG,
	CORE_SONG,
	CORE_SONG_ARTIST
WHERE CORE_SONG.ID = CORE_PLAYLIST_SONG.SONG_ID
	AND CORE_PLAYLIST.ID = CORE_PLAYLIST_SONG.PLAYLIST_ID
	AND CORE_PLAYLIST.ID = 87
	AND CORE_SONG_ARTIST.SONG_ID = CORE_SONG.ID;


SELECT CORE_SONG.GENRE_ID,
	CORE_GENRE.TITLE,
	CORE_SONG.NAME,
	CORE_PLAYLIST_SONG.PLAYLIST_ID
FROM CORE_PLAYLIST_SONG,
	CORE_SONG,
	CORE_GENRE
WHERE CORE_PLAYLIST_SONG.SONG_ID = CORE_SONG.ID
	AND CORE_SONG.GENRE_ID = CORE_GENRE.ID
	AND CORE_PLAYLIST_SONG.PLAYLIST_ID = 46

