SELECT CORE_SONG.NAME AS SONG,CORE_PLAYLIST.NAME AS PLAYLIST,
	COUNT(CORE_SONGLIKE.ID) AS LIKES
FROM CORE_SONG,
	CORE_PLAYLIST,
	CORE_PLAYLIST_SONG,
	CORE_SONGLIKE
WHERE CORE_PLAYLIST.ID = CORE_PLAYLIST_SONG.PLAYLIST_ID
	AND CORE_SONG.ID = CORE_PLAYLIST_SONG.SONG_ID
	AND CORE_SONGLIKE.SONG_ID = CORE_SONG.ID
GROUP BY SONG,
	CORE_PLAYLIST.NAME