SELECT CORE_PLAYLIST.NAME AS PLAYLISTNAME,
	CORE_SONG_ARTIST.ARTIST_ID,
	CORE_ARTIST.NAME AS ARTISTNAME,
	CORE_GENRE.ID AS GENRE_ID
FROM CORE_PLAYLIST_SONG,
	CORE_PLAYLIST,
	CORE_SONG_ARTIST,
	CORE_ARTIST,
	CORE_GENRE,
	CORE_SONG
WHERE CORE_SONG_ARTIST.SONG_ID = CORE_PLAYLIST_SONG.SONG_ID
	AND CORE_ARTIST.ID = CORE_SONG_ARTIST.ARTIST_ID
	AND CORE_SONG.ID = CORE_PLAYLIST_SONG.SONG_ID
	AND CORE_SONG.GENRE_ID = CORE_GENRE.ID