CREATE VIEW [PLAYLIST SONG ARTIST] AS
SELECT CORE_SONG.ID AS SONG_ID,
	CORE_SONG.NAME AS SONG_NAME,
	CORE_ARTIST.ID AS ARTIST_ID,
	CORE_ARTIST.NAME AS ARTIST_NAME,
	CORE_PLAYLIST.ID AS PLAYLIST_ID,
	CORE_PLAYLIST.NAME AS PLAYLIST_NAME
FROM CORE_SONG,
	CORE_SONG_ARTIST,
	CORE_ARTIST,
	CORE_PLAYLIST_SONG,
	CORE_PLAYLIST
WHERE CORE_SONG_ARTIST.ARTIST_ID = CORE_ARTIST.ID
	AND CORE_SONG.ID = CORE_PLAYLIST_SONG.SONG_ID
	AND CORE_PLAYLIST_SONG.PLAYLIST_ID = CORE_PLAYLIST.ID